### ISSUE TITLE
has() and get() function not compatible with psr/container 1.1.1 using declare_strict or preload

### ISSUE THREAD

**Issue by lampi87** [laminas/laminas-crypt#23] opened 2022-06-10 16:19 UTC
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.8.0

#### Summary

Current implementation of has() and get() functions not compatible with psr/container 1.1.1 using opcache.preload or declare_strict

PHP Fatal error:  Declaration of Laminas\Crypt\Symmetric\PaddingPluginManager::has(string $id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /var/www/.../vendor/laminas/laminas-crypt/src/Symmetric/PaddingPluginManager.php on line 32
PHP Fatal error:  Declaration of Laminas\Crypt\Symmetric\PaddingPluginManager::get($id) must be compatible with Psr\Container\ContainerInterface::get(string $id): object in /var/www/.../vendor/laminas/laminas-crypt/src/Symmetric/PaddingPluginManager.php on line 43

Same for has and get in Laminas\Crypt\SymmetricPluginManager

**Comment by Ocramius** [comment] 2022-06-10 16:28
Hmm, what version of `laminas/laminas-servicemanager` is installed?

**Comment by lampi87** [comment] 2022-06-10 16:41
Version 3.11.2 of `laminas/laminas-servicemanager` is installed.

If I compare psr/container 1.1.2 and given files/functions:

`public function has($id)` vs `public function has(string $id)`

**Comment by Ocramius** [comment] 2022-06-10 17:10
Wait, so your local PSR container has a different signature than the one in the upstream reposi? O.o

See https://github.com/php-fig/container/blob/1.1.2/src/ContainerInterface.php#L22

**Comment by lampi87** [comment] 2022-06-11 05:45
Both lines where copied from checkout out files in my local vendor dir.

I'm not sure why `: object` or `: bool` is mentioned as required in logs

**Comment by Ocramius** [comment] 2022-06-11 08:19
I suspect that your `ContainerInterface` is declared by a third party: try using reflection to find where it is loaded from.

Meanwhile, closing here, since the issue is not in this package.

**Closed as completed by Ocramius** 2022-06-11 08:19 UTC
Labels: BC Break

**Comment by lampi87** [comment] 2022-06-11 08:43
You're right. The issue is related to package `laminas/laminas-inputfilter`. The File `.psr-container-stub.php` has a more strict declaration for Psr\Container\ContainerInterface.
I'll create an issue there

**Comment by Ocramius** [comment] 2022-06-11 08:51
@lampi87 that file is **NOT** autoloaded
